name: Blog Posts Update

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 */1 * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: RUN
        run: |
          java -jar build/libs/0n1dev-1.0-SNAPSHOT.jar
      - name: Commit README
        run: |
          git add .
          git diff
          git config --local user.email "all_mind@naver.com"
          git config --local user.name "0n1dev"
          git commit -m "Update README.md"
          git push